name: "Kurt's Travel"
favicon: null
layout_spectrum: 0.5668789432384074
typography_spectrum: 0.3284685602411628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.12030694796703756
  lightness: 0.3388370245229453
  saturation: 0.5960140021052212
  rhythmicContrast: 0.9541501314379275
purpose: []
